[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "cli-main"
path = "src/main.rs"

[[bin]]
name = "cli-tool"
path = "src/bin/tool.rs"

[dependencies]
core = { path = "../core" }
clap = { workspace = true }
anyhow = { workspace = true }
