[target.wasm32-unknown-unknown]
runner = 'wasm-bindgen-test-runner'

[alias]
compile = "run --package xtask -- compile"
lint    = ["run", "--package", "xtask", "--", "lint"]
xt-test = "run --package xtask -- test"
xt-pkg  = "run --package xtask -- package"
