name: CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    # Enhanced npm cache with lockfile hash
    - name: Cache node_modules
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-${{ matrix.node-version }}-
          ${{ runner.os }}-node-
    
    # Setup Rust toolchain for cargo-make
    - name: Setup Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
    
    - name: Install cargo-make
      run: cargo install cargo-make

    - name: Rust Cache
      uses: Swatinem/rust-cache@v2
    
    - name: Install dependencies
      run: npm ci
    
    # Setup headless display before running any VS Code tests (Linux only)
    - name: Setup headless display (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        sleep 3
        echo "DISPLAY=:99.0" >> $GITHUB_ENV
    
    - name: Compile TypeScript
      run: npm run compile-tests
    
    - name: Compile extension
      run: npm run compile
    
    - name: Run linter
      run: npm run lint
    
    - name: Run tests
      run: npm test
      env:
        # Needed for headless VS Code testing
        DISPLAY: :99.0

  build-package:
    name: Build Extension Package
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    # Enhanced npm cache
    - name: Cache node_modules
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-20.x-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-20.x-
          ${{ runner.os }}-node-
    
    # Cache webpack build artifacts
    - name: Cache webpack build
      uses: actions/cache@v4
      with:
        path: |
          out/
          dist/
          .webpack-cache/
        key: ${{ runner.os }}-webpack-${{ hashFiles('webpack.config.js', 'tsconfig.json', 'src/**/*.ts') }}
        restore-keys: |
          ${{ runner.os }}-webpack-
    
    - name: Install dependencies
      run: npm ci
    
    - name: Package extension
      run: npx @vscode/vsce package
    
    - name: Upload extension artifact
      uses: actions/upload-artifact@v4
      with:
        name: cargo-tools-extension
        path: '*.vsix'
        retention-days: 30

  security:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    # Enhanced npm cache
    - name: Cache node_modules
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-20.x-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-20.x-
          ${{ runner.os }}-node-
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run security audit
      run: npm audit --audit-level=moderate
